class DroneState:
    EMERGENCY_LAND = "Emergency Land"
    LAND = "Land"
    GROUND = "Ground"
    TAKE_OFF = "Take Off"
    HOVER = "Hover"
    SCAN = "Scan"
    FLY_SLOW = "Fly Slow"
    FLY_FAST = "Fly Fast"
    BRAKe = "Brake"
    RTH = "RTH"
    LOW_BAT = "Low Battery"
    MINOR_BUMP = "Minor Bump"
    MAJOR_BUMP = "Major Bump"
    REVERSE = "Reverse"
    EMERGENCY = "Emergency"
